# dependabot.yml file with updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'friday'
    ignore:
      - dependency-name: "glob-parent"
        versions: ["5.x", "6.x"]
      - dependency-name: "yargs-parser"
        versions: ["5.x"]
    open-pull-requests-limit: 10
    allow:
      - dependency-type: 'direct'
